language: ruby
cache: bundler
sudo: required
dist: trusty
before_install:
  - gem install bundler
  - sudo rm -rf /var/lib/cassandra/*
  - wget https://archive.apache.org/dist/cassandra/3.7/apache-cassandra-3.7-bin.tar.gz && tar -xvzf apache-cassandra-3.7-bin.tar.gz && sudo sh apache-cassandra-3.7/bin/cassandra -R && sleep 15
rvm:
  - 2.3.1
  - 2.2.5
  - 2.1.9
  # Temoprarily disabled until we get this working since it slows down tests
  # - jruby-9.0.5.0
matrix:
  allow_failures:
    - rvm: jruby-9.0.5.0
script:
  - sed -i '/^--tag/d' .rspec
  - bundle exec rspec
